### ISSUE TITLE
Maybe reconcile the use of "scm" and "vcs" in runbld config and output

### ISSUE THREAD

**Issue by leathekd** [elastic/runbld#72]
`scm` is used to tell runbld what repo/branch to clone while `vcs` is used to hold the commit log of the specified branch.  There's also a bit of scm/vcs related data in the `build` section that is populated by parsing the job-name (I don't think that needs to change, necessarily, just pointing it out).

We should think about a naming scheme that clarifies what all of these are for.  (note that some changes may impact the ES mapping which may influence what we should do)

**Comment by drewr** [comment]
I _think_ we can leave the ES schema alone since it still only uses `vcs`.  At least I think it still does.  Ultimately as an output the only thing we care about is what unique code point was tested.  Everything else is just fluff for ease of reporting.  Internal to runbld, `scm` took on the meaning as a config parameter to say, "whence did my `vcs` come?"

Now however I'm starting to notice that the two acronyms really aren't interchangeable, even though we often use them that way.

* **VCS**: Version Control System
* **SCM**: Source Control Management

In this sense, we kind of are using them in the right way.  `scm` refers to how we bootstrap the `vcs`.  So I dunno, maybe I raised a non-issue.  I'll let @michaelbaamonde chime in.

**Comment by drewr** [comment]
Looking at some JJB today, I think this is pretty obvious now. **I**t's **W**hat **J**enkins **U**ses.

**Comment by michaelbaamonde** [comment]
> scm refers to how we bootstrap the vcs

That was my thought, yeah. That said, I don't have a strong opinion here and won't complain if you guys want to use `vcs` across the board.

**Comment by drewr** [comment]
The demarcation is a bit clearer than at first. I think we can leave this as not actionable for now and if we do want to reconcile it later just mention the issue.
